version: '3.8'

services:
  server:
    build:
      context: .                
      dockerfile: Dockerfile
    container_name: storage_server_container
    ports:
      - "${BASIC_SERVER_PORT:-8090}:8090"  
    environment:
      - BASIC_SERVER_PORT=8090
      - STORAGE_FILE_PATH=/app/cmd/slice_storage.json
    volumes:
      - ./cmd:/app/cmd:consistent
    stop_signal: SIGINT
    stop_grace_period: 30s
 